apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-app
  template:
    metadata:
      labels:
        app: project-app
    spec:
      containers:
      - name: project-container
        image: 659194519955.dkr.ecr.us-east-1.amazonaws.com/harman-repo:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: project-deployment
spec:
  selector:
    app: project-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

