# Creation of the kubernetes service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: harman
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::659194519955:role/harman-eks-node
